### PR TITLE
Cover with core redesign

### PR DESCRIPTION
**Pull request by smathermather**
Working on the cover / external frame as well as doing some refinements to the internal structure.
image

### CODE REVIEW

**Comment by smathermather** [comment]
image

**Comment by smathermather** [comment]
Print of top piece underway:
image

image

image

**Comment by smathermather** [comment]
Now the base plate and shell printing:

**Comment by smathermather** [comment]
Ok, there are some things to clean up: how to connect top and bottom, reduce holes in both, and a couple other things, but this is ready to merge. I'll open an issue for the other things which need fixed and then work on a separate pull request:
image

image

image

image

image

**Comment by ivangayton** [comment]
All changes are in the hardware directory, so safe to merge.

**Pull request merged**
