### PR TITLE
add internal spokes and pole structures

### PR DESCRIPTION
**Pull request by smathermather**
@ivangayton -- this requires a little more work to fix the distances for the spokes.

### CODE REVIEW

**Comment by smathermather** [comment]
Lots of parameterization still needed.

**Comment by ivangayton** [comment]
Threads, huh? I've always been skeptical of printing threads. Not because it's not possible (it is possible), but because putting threads in plastic is usually a sign that you've got a poor design. 

Bottom line: plastic doesn't hold threads very well. Internal slightly better than external, but nevertheless. Threads in plastic are incredibly liable to stripping. You can always make the pitch gigantic; you can make a bolt or threaded hole the size of a carriage bolt, but at that point what's the advantage compared to a much smaller metal part?

I'm much more inclined to try to design in such as way as to be able to embed nuts for internal threading, and mount bolts or threaded rods for external.

That said, I don't know what you have in mind yet, so let's see what you're thinking!

**Comment by smathermather** [comment]
I don't know what you're talking about, Ivan
image

In all seriousness, the threaded bits save me time for now in mocking things up, but ultimately will be replaced by real hardware. In this case, they let me quickly mock up and tap into the existing backpack hardware and envision what the fully FOSS version of the backpack looks like.

More importantly, they help with quick mock-ups of full(ish) camera ball arrays:
image

**Comment by hcwinsemius** [comment]
Sounds like something to talk about rather than email or git-discuss.
Tomorrow on the agenda gents!!

Op ma 14 dec. 2020 19:02 schreef Stephen Mather <notifications@github.com>:

**Comment by ivangayton** [comment]
Ok, I have to admit, that size thread (which actually is the size of a carriage bolt!) is sometimes a reasonble option! It's actually big enough that there may be a good reason to sacrifice strength for lower weight! 

That being said, you could probably buy a [length of threaded nylon rod for a few bucks](https://www.usplastic.com/catalog/item.aspx?itemid=63163). Survey antennas usually 5/8 x 11".

**Comment by smathermather** [comment]
I am going to close this. Going a different direction in the generation of the base.

**Pull request closed without merging**
